# Generated by Django 2.2.1 on 2020-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comp_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
